services:
  olympia-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olympia-frontend-container
    ports:
      - "4000:4000"
    restart: always
    environment:
      - NODE_ENV=production
